version: "3.9"

networks:
  dotnet-otel-demo:
  
services:
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "2@LaiNw)PDvs^t>L!Ybt]6H^%h3U>M"
        ACCEPT_EULA: "Y"
    networks:
      - dotnet-otel-demo

  identity-server:
    build:
      context: ./src/IdentityServer
      dockerfile: Dockerfile
    ports:
     - "5001:80"
    networks:
      - dotnet-otel-demo

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.59.0
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55679:55679" # zpages extension
      - "4317:4317"   # OTLP gRPC receiver
    environment:
      - DYNATRACE_OTLP_INGEST_ENDPOINT=${DYNATRACE_OTLP_INGEST_ENDPOINT}
      - DYNATRACE_OTEL_TOKEN=${DYNATRACE_OTEL_TOKEN}
    depends_on:
      - jaeger
    networks:
      - dotnet-otel-demo

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"
    networks:
      - dotnet-otel-demo
