receivers:
  otlp:
    protocols:
      grpc:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
      
  otlphttp:
    endpoint: $DYNATRACE_OTLP_INGEST_ENDPOINT
    headers:
      Authorization: "Api-Token $DYNATRACE_OTEL_TOKEN"
      
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,jaeger,otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlphttp]
