receivers:
  otlp:
    protocols:
      grpc:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
      
  otlphttp:
    endpoint: <your-observability-back-end-otlp-endpoint
    headers:
      Authorization: "<your-observability-back-end-authorization"
      
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, otlphttp]
      # uncomment to send traces also via HTTP to your back-end
      # exporters: [logging,jaeger,otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp]
      # uncomment to send metrics also via HTTP to your back-end
      # exporters: [logging, otlphttp]
    logs:
      receivers: [otlp]
      exporters: [logging, otlphttp]
