receivers:
  otlp:
    protocols:
      grpc:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  logging:
    loglevel: debug
  otlphttp:
    endpoint: "https://<o11y-back-end>/api/v2/otlp"
    headers:
      Authorization: "<some-api-token>"
    

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,jaeger,otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [logging]