receivers:
  otlp:
    protocols:
      grpc:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,jaeger]
    metrics:
      receivers: [otlp]
      exporters: [logging]